#!/usr/bin/python3
# -*- python -*-

import os, sys
from subprocess import Popen, PIPE


def pages_1_7(p):
    print()
    print(center('\033[01mBootprocessen\033[00m'))
    def p2():
        print()
        print('\033[01mBIOS\033[21m')
        print()
    def p3():
        print('-  Initiserar viktigt hårdvara såsom RAM-minnet')
    def p4():
        print('-  Gör det möjligt för operativsystemet att kommunicera med BIOS för att använda hårdvara')
    def p5():
        print('-  Sätter CPU:ns instruktionspekare till början av första hårddisken')
    def p6():
        print('   -  Kollar första att enhet innehåller ett program')
    def p7():
        print('   -  Användaren kan välja en annan enhet att köra')
    pp(locals(), p)


def pages_8_12(p):
    print()
    print(center('\033[01mBootprocessen\033[00m'))
    def p8():
        print()
        print('\033[01mBoot manager\033[21m')
        print()
    def p9():
        print('-  440 byte i början av hårddisken')
    def p10():
        print('-  Hitta en körbar primär partition')
    def p11():
        print('-  Initisera stacken')
    def p12():
        print('-  Sätter CPU:ns instruktionspekare till början av en körbar partition')
    pp(locals(), p)


def pages_13_19(p):
    print()
    print(center('\033[01mBootprocessen\033[00m'))
    def p13():
        print()
        print('\033[01mBootloader\033[21m')
        print()
    def p14():
        print('-  Större program')
    def p15():
        print('-  Har ofta en egen partition')
    def p16():
        print('-  Tillåter användaren att välja operativsystem')
    def p17():
        print('   -  Kan kräva kedjeladdning (chain loading)')
    def p18():
        print('   -  Kan vara små program')
    def p19():
        print('-  Tillåter användaren att välja hur operativsystemet ska startas')
    pp(locals(), p)


def pages_20_30(p):
    print()
    print(center('\033[01mBootprocessen\033[00m'))
    def p20():
        print()
        print('\033[01mOperativsystemskärnan\033[21m')
        print()
    def p21():
        print('-  Ligger ofta som en fil i bootloader:ns partition')
    def p22():
        print()
        print()
        print('\033[01mInitramfs/Initrd/Initcpio\033[21m')
        print()
        print('-  Det första som starts av operativsystemskärnan')
    def p23():
        print('-  Ligger ofta som en fil i bootloader:ns partition')
    def p24():
        print('-  Minimal installation av operativsystemet')
    def p25():
        print('   -  Dekryptera partitioner')
    def p26():
        print('   -  Monterar partitioner')
    def p27():
        print()
        print()
        print('\033[01mInit + RC\033[21m')
        print()
    def p28():
        print('   -  Initiserar arbetsmiljön')
    def p29():
        print('   -  Startar daemoner')
    def p30():
        print('   -  Startar loginhanterare')
    pp(locals(), p)


pageses, gs = [], globals()
for pages in [name for name in dir() if name.startswith('pages_')]:
    _, first, last = pages.split('_')
    for i in range(int(first), int(last) + 1):
        code = 'page_%i = lambda : pages_%i_%i(%i)\n' % (i, int(first), int(last), i)
        code = compile(code, '-generated', 'exec')
        exec(code, globals())

def center(text):
    length, escape = 0, False
    for c in text:
        if c == '\033':
            escape = True
        elif escape:
            escape = c != 'm'
        else:
            length += 1
    length = (width - length) // 2
    return ' ' * length + text

def h(text, cond):
    if cond:
        return '\033[01;31m%s\033[m' % text
    else:
        return text

def pp(local, page):
    for p in range(1, page + 1):
        if ('p%i' % p) in local:
            if p == page:
                print('\033[01;31m', end = '')
            local['p%i' % p]()
            if p == page:
                print('\033[m', end = '')

pages, gs = [], globals()
for i in range(len([name for name in dir() if name.startswith('page_')])):
    pages.append(gs['page_' + str(i + 1)])

print('\033[?25l\033[H\033[2J', end = '')
Popen('stty -echo -icanon'.split(' '), stderr = sys.stderr)
size = Popen('stty size'.split(' '), stderr = sys.stderr, stdout = PIPE).communicate()[0]
(height, width) = size.decode('utf-8', 'replace').split('\n')[0].split(' ')
height, width = int(height), int(width)

pid = os.fork()
if pid != 0:
    try:
        while True:
            (reaped, status) = os.wait()
            if reaped == pid:
                break
    except:
        pass
    if status == 0:
        print('\033[H\033[2J', end = '')
    print('\033[?25h', end = '', flush = True)
    Popen('stty echo icanon'.split(' '), stderr = sys.stderr)
    sys.exit(status)

old_print = print
def print(text = '', *, end = '\n', flush = True):
    old_print(text + '\033[K', end = end, flush = flush)

page, page_last = (1 if len(sys.argv) == 1 else int(sys.argv[1])), len(pages) - 1
page -= 1
while True:
    old_print('\033[H', end = '')
    pages[page]()
    bar, start, switched = int(width * page / page_last), width - len(str(page + 1)), False
    text = '\033[J\033[%i;%iH\033[45m%s\033[m\033[%i;%iH\033[45;30m' % (height, 0, ' ' * bar, height, start)
    for i, c in enumerate(str(page + 1)):
        if start + i > bar:
            if not switched:
                switched = True
                text += '\033[00;35m'
        text += c
    old_print('%s\033[00m' % text, end = '', flush = True)
    while True:
        text = sys.stdin.buffer.read(1)
        if text in b'\n C':
            if page == page_last:
                continue
            page += 1
        elif text in b'\x7fD':
            if page == 0:
                continue
            page -= 1
        elif text in b'\x04':
            sys.exit(0)
        elif text in b'\x0c':
            pass
        else:
            continue
        break

